### ISSUE TITLE
Sdd support for 64x32 I2C Display

### ISSUE THREAD

**Issue by mdmiko** [rm-hull/luma.oled#147]
With luma lib, the display works but, y offset seems to be negative

As tested on u8glib, only change from 64x48 is multiplex
from 0x02f to 0x01f

http://www.buydisplay.com/default/0-49-inch-oled-display-module-64x32-pixel-ssd1306-spi-i2c-white-on-black

**Comment by rm-hull** [comment]
So if you can confirm changing your local version (e.g `/usr/local/lib/python27/luma/oled/device.py`) of https://github.com/rm-hull/luma.oled/blob/master/luma/oled/device.py#L125-L130 to read:

```python
        settings = {
            (128, 64): dict(multiplex=0x3F, displayclockdiv=0x80, compins=0x12),
            (128, 32): dict(multiplex=0x1F, displayclockdiv=0x80, compins=0x02),
            (96, 16): dict(multiplex=0x0F, displayclockdiv=0x60, compins=0x02),
            (64, 48): dict(multiplex=0x2F, displayclockdiv=0x80, compins=0x12),
            (64, 32): dict(multiplex=0x1F, displayclockdiv=0x80, compins=0x12)  # add this line
        }.get((width, height))
```

works, and running (from the **luma.examples** repo):

    $ python examples/demo.py --width=64 --height=32

It should look like (pic would be good):

![luma_000001](https://cloud.githubusercontent.com/assets/1915543/24840152/bb30009a-1d5f-11e7-805b-e931e0cd4a73.png)

Then I will add it support to the library and push out a new release.

**Comment by mdmiko** [comment]
thanks, for today I can only run a emulation test: python examples/clock.py
--width 64 --height 32 --display capture
It works: https://transfer.sh/PJF3x/luma_000005.png

2017-04-09 21:06 GMT+02:00 Richard Hull <notifications@github.com>:

**Comment by thijstriemstra** [comment]
fixed with #144?

**Comment by rm-hull** [comment]
No not fixed. Fix is trivial though: it needs `(64, 32): dict(multiplex=0x1F, displayclockdiv=0x80, compins=0x12)` adding to the init method and then someone to verify that it works on a real device (not an emulator).

**Comment by mdmiko** [comment]
It works.

Il 11 apr 2017 10:20 PM, "Richard Hull" <notifications@github.com> ha
scritto:

**Comment by rm-hull** [comment]
@mdmiko - release 2.2.7 of luma.oled should now support 64x32 SSD1306
